import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  Mail, 
  Send, 
  Sparkles, 
  CheckCircle, 
  AlertTriangle, 
  FileText, 
  User, 
  ArrowRight, 
  Clock, 
  RefreshCw, 
  Trash2, 
  CheckCircle2, 
  FolderPlus,
  Loader2,
  Lock,
  ListFilter,
  Check
} from 'lucide-react';
import { getGmailAccessToken, signInWithGoogleForGmail, setGmailAccessToken } from '../firebase';
import { CSVFile } from '../types';

interface GmailCenterProps {
  activeFile: CSVFile | null;
  isDarkMode: boolean;
  accentClass: string;
  onNavigate: (tab: string) => void;
  onAddActivity: (action: string) => void;
}

export default function GmailCenter({ 
  activeFile, 
  isDarkMode, 
  accentClass, 
  onNavigate,
  onAddActivity
}: GmailCenterProps) {
  const [token, setToken] = useState<string | null>(getGmailAccessToken());
  const [isAuthorizing, setIsAuthorizing] = useState(false);
  const [activeSubTab, setActiveSubTab] = useState<'compose' | 'contacts' | 'sent'>('compose');
  
  // Compose form states
  const [toEmail, setToEmail] = useState('');
  const [subject, setSubject] = useState('');
  const [emailBody, setEmailBody] = useState('');
  const [isSending, setIsSending] = useState(false);
  const [sendSuccess, setSendSuccess] = useState<string | null>(null);
  const [sendError, setSendError] = useState<string | null>(null);

  // Template pre-selection
  const [selectedTemplate, setSelectedTemplate] = useState<'audit_summary' | 'hygiene_report' | 'custom'>('audit_summary');

  // Contact list extracted from the active CSV
  const [extractedEmails, setExtractedEmails] = useState<{ email: string; name: string; row: number }[]>([]);
  const [selectedContact, setSelectedContact] = useState<string>('');

  // History / sent emails local cache
  const [sentHistory, setSentHistory] = useState<{ id: string; to: string; subject: string; date: string; status: 'sent' | 'failed' }[]>([
    { id: '1', to: 'audit-team@company.com', subject: 'Initial CSV Integrity Verification Report', date: 'Just now', status: 'sent' }
  ]);

  // Loading recently sent messages from Gmail API
  const [recentGmailMessages, setRecentGmailMessages] = useState<any[]>([]);
  const [isLoadingGmail, setIsLoadingGmail] = useState(false);

  // Load token on mount
  useEffect(() => {
    const t = getGmailAccessToken();
    if (t) {
      setToken(t);
    }
  }, []);

  // Extract email addresses from active file columns
  useEffect(() => {
    if (!activeFile) return;

    const emailsFound: { email: string; name: string; row: number }[] = [];
    const emailRegex = /[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/g;

    activeFile.rows.forEach((row, idx) => {
      // Look in all values of the row
      Object.entries(row).forEach(([colName, val]) => {
        if (typeof val === 'string') {
          const matches = val.match(emailRegex);
          if (matches) {
            matches.forEach(email => {
              // Guess name from adjacent columns or customer name
              const nameGuess = row['Customer_Name'] || row['Name'] || row['Username'] || 'Valued Client';
              if (!emailsFound.some(e => e.email.toLowerCase() === email.toLowerCase())) {
                emailsFound.push({
                  email,
                  name: nameGuess,
                  row: idx + 1
                });
              }
            });
          }
        }
      });
    });

    setExtractedEmails(emailsFound);
    if (emailsFound.length > 0) {
      setSelectedContact(emailsFound[0].email);
      setToEmail(emailsFound[0].email);
    }
  }, [activeFile]);

  // Pre-populate templates
  useEffect(() => {
    if (!activeFile) return;

    const criticalCount = activeFile.issues.filter(i => i.severity === 'critical').length;
    const warningCount = activeFile.issues.filter(i => i.severity === 'warning').length;
    const infoCount = activeFile.issues.filter(i => i.severity === 'info').length;

    if (selectedTemplate === 'audit_summary') {
      setSubject(`[Audit Summary] ${activeFile.name} - Quality Check Passed: ${activeFile.score}%`);
      setEmailBody(`
<h2>CSV Compliance & Integrity Report</h2>
<p>Hello,</p>
<p>This is an automated data hygiene report for the dataset <strong>"${activeFile.name}"</strong> generated by <strong>CSV Auditor Pro</strong>.</p>

<table style="border-collapse: collapse; width: 100%; max-width: 500px; margin: 15px 0;">
  <tr style="background-color: #f8fafc;">
    <th style="border: 1px solid #e2e8f0; padding: 8px; text-align: left;">Metric</th>
    <th style="border: 1px solid #e2e8f0; padding: 8px; text-align: left;">Value</th>
  </tr>
  <tr>
    <td style="border: 1px solid #e2e8f0; padding: 8px;"><strong>File Integrity Score</strong></td>
    <td style="border: 1px solid #e2e8f0; padding: 8px; color: ${activeFile.score >= 80 ? '#10b981' : '#f59e0b'}; font-weight: bold;">${activeFile.score}%</td>
  </tr>
  <tr>
    <td style="border: 1px solid #e2e8f0; padding: 8px;">Total Data Rows</td>
    <td style="border: 1px solid #e2e8f0; padding: 8px;">${activeFile.rows.length}</td>
  </tr>
  <tr>
    <td style="border: 1px solid #e2e8f0; padding: 8px; color: #ef4444;">Critical Duplicates/Errors</td>
    <td style="border: 1px solid #e2e8f0; padding: 8px; color: #ef4444; font-weight: bold;">${criticalCount}</td>
  </tr>
  <tr>
    <td style="border: 1px solid #e2e8f0; padding: 8px; color: #f59e0b;">Standardization Warnings</td>
    <td style="border: 1px solid #e2e8f0; padding: 8px; color: #f59e0b;">${warningCount}</td>
  </tr>
  <tr>
    <td style="border: 1px solid #e2e8f0; padding: 8px; color: #3b82f6;">Compliance Notices</td>
    <td style="border: 1px solid #e2e8f0; padding: 8px; color: #3b82f6;">${infoCount}</td>
  </tr>
</table>

<p>To inspect or clean these findings, please sign in to the CSV Auditor Pro workspace.</p>
<hr style="border: none; border-top: 1px solid #e2e8f0; margin: 20px 0;" />
<p style="font-size: 11px; color: #64748b;">This email was sent securely via Gmail API Integration with CSV Auditor Pro.</p>
      `.trim());
    } else if (selectedTemplate === 'hygiene_report') {
      setSubject(`[Data Hygiene Notification] Request for Data Correction: ${activeFile.name}`);
      setEmailBody(`
<h2>Data Hygiene Correction Request</h2>
<p>Hello,</p>
<p>During our automated audit check of the <strong>"${activeFile.name}"</strong> records, we identified columns that require manual verification or standardization.</p>
<p>Our algorithms flagged <strong>${criticalCount} critical rows</strong> containing duplicated primary keys, inconsistent contact formatting, or unmapped currency fields.</p>
<p>Kindly download the latest standardized export from the CSV Auditor panel or reply to this thread to confirm these corrections.</p>
<br/>
<p>Best regards,<br/>Data Integrity Assurance Team</p>
      `.trim());
    } else {
      setSubject('');
      setEmailBody('');
    }
  }, [activeFile, selectedTemplate]);

  // Load actual Gmail messages if authorized
  useEffect(() => {
    if (token) {
      fetchGmailSentList();
    }
  }, [token]);

  // Fetch recent sent messages using Gmail API
  const fetchGmailSentList = async () => {
    if (!token) return;
    setIsLoadingGmail(true);
    try {
      const res = await fetch('https://www.googleapis.com/gmail/v1/users/me/messages?maxResults=5&q=subject:Audit', {
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });
      if (res.status === 401) {
        // Token expired
        setToken(null);
        setGmailAccessToken(null);
        return;
      }
      if (!res.ok) throw new Error('Failed to fetch Gmail sent list');
      const data = await res.json();
      
      if (data.messages && data.messages.length > 0) {
        // Fetch details for each message
        const detailedMsgs = await Promise.all(
          data.messages.map(async (m: { id: string }) => {
            const detailRes = await fetch(`https://www.googleapis.com/gmail/v1/users/me/messages/${m.id}`, {
              headers: { 'Authorization': `Bearer ${token}` }
            });
            if (detailRes.ok) {
              const detail = await detailRes.json();
              const headers = detail.payload?.headers || [];
              const to = headers.find((h: any) => h.name.toLowerCase() === 'to')?.value || 'Unknown Recipient';
              const subjectHeader = headers.find((h: any) => h.name.toLowerCase() === 'subject')?.value || 'No Subject';
              const date = headers.find((h: any) => h.name.toLowerCase() === 'date')?.value || 'Date Unknown';
              return {
                id: m.id,
                to,
                subject: subjectHeader,
                date: new Date(date).toLocaleString([], { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }),
                status: 'sent'
              };
            }
            return null;
          })
        );
        setRecentGmailMessages(detailedMsgs.filter(m => m !== null));
      } else {
        setRecentGmailMessages([]);
      }
    } catch (err) {
      console.error('Error listing Gmail communications:', err);
    } finally {
      setIsLoadingGmail(false);
    }
  };

  // Google OAuth flow for Gmail
  const handleAuthorize = async () => {
    setIsAuthorizing(true);
    try {
      const result = await signInWithGoogleForGmail();
      if (result) {
        setToken(result.accessToken);
        onAddActivity(`Connected Google Gmail account securely`);
      }
    } catch (err: any) {
      console.error('Google Gmail auth failed:', err);
      alert('Gmail Authorization failed. Please verify popup settings or scopes.');
    } finally {
      setIsAuthorizing(false);
    }
  };

  const handleDisconnect = () => {
    if (window.confirm('Are you sure you want to disconnect Gmail integration? This will remove the API connection.')) {
      setToken(null);
      setGmailAccessToken(null);
      onAddActivity(`Disconnected Google Gmail integration`);
    }
  };

  // Build secure web-safe Base64 RFC 2822 email payload
  const buildRawEmail = (to: string, sub: string, body: string) => {
    const rfcMessage = [
      `To: ${to}`,
      `Subject: ${sub}`,
      'MIME-Version: 1.0',
      'Content-Type: text/html; charset=utf-8',
      '',
      body
    ].join('\r\n');

    const base64 = btoa(unescape(encodeURIComponent(rfcMessage)));
    return base64.replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
  };

  // Send the drafted email securely
  const handleSendEmail = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!token) return;
    if (!toEmail) {
      setSendError('Please enter a recipient email.');
      return;
    }

    // MANDATORY confirmation dialog for sending emails on user behalf (as instructed by skill)
    const confirmed = window.confirm(`Confirm: Send this compliance email to ${toEmail} using your Gmail account?`);
    if (!confirmed) return;

    setIsSending(true);
    setSendSuccess(null);
    setSendError(null);

    try {
      const raw = buildRawEmail(toEmail, subject, emailBody);
      const response = await fetch('https://www.googleapis.com/gmail/v1/users/me/messages/send', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ raw })
      });

      if (!response.ok) {
        throw new Error('Gmail API responded with an error. Please verify scope permissions.');
      }

      setSendSuccess(`Compliance report successfully dispatched to ${toEmail}!`);
      onAddActivity(`Sent email report: "${subject}" to ${toEmail}`);
      
      // Update local sent history
      setSentHistory(prev => [
        { id: `sent-${Date.now()}`, to: toEmail, subject, date: 'Just now', status: 'sent' },
        ...prev
      ]);

      // Clear non-template values if custom
      if (selectedTemplate === 'custom') {
        setToEmail('');
        setSubject('');
        setEmailBody('');
      }

      // Refresh real Gmail sent list
      fetchGmailSentList();

    } catch (err: any) {
      console.error('Gmail send failure:', err);
      setSendError(err.message || 'Gmail transmission failed.');
      setSentHistory(prev => [
        { id: `fail-${Date.now()}`, to: toEmail, subject, date: 'Just now', status: 'failed' },
        ...prev
      ]);
    } finally {
      setIsSending(false);
    }
  };

  const selectContactItem = (email: string) => {
    setToEmail(email);
    setSelectedContact(email);
    setActiveSubTab('compose');
  };

  return (
    <div className="space-y-6">
      
      {/* Top Banner introducing Gmail Integration */}
      <div className={`p-6 rounded-2xl border ${isDarkMode ? 'bg-gradient-to-br from-indigo-950/20 to-slate-900 border-slate-800' : 'bg-gradient-to-br from-indigo-50 to-white border-slate-200'} shadow-xs flex flex-col md:flex-row gap-6 justify-between items-start md:items-center`}>
        <div className="space-y-1.5 max-w-2xl">
          <div className="flex items-center gap-2">
            <div className="p-1.5 bg-indigo-500/10 text-indigo-500 rounded-lg">
              <Mail className="w-5 h-5 text-indigo-500 dark:text-indigo-400" />
            </div>
            <h3 className="font-bold text-sm tracking-tight">Gmail Compliance Hub</h3>
          </div>
          <p className="text-xs text-slate-400 leading-relaxed">
            Dispatch audit findings, data hygiene status notifications, and corrective warnings securely. Your communications utilize secure, user-approved Gmail API scopes directly from your web workstation.
          </p>
        </div>
        
        {token ? (
          <div className="flex items-center gap-3">
            <div className={`px-3 py-1.5 rounded-lg border text-xs font-bold flex items-center gap-1.5 ${isDarkMode ? 'bg-emerald-500/10 border-emerald-500/20 text-emerald-400' : 'bg-emerald-50 border-emerald-200 text-emerald-700'}`}>
              <CheckCircle2 className="w-4 h-4 text-emerald-500" /> Connected
            </div>
            <button
              onClick={handleDisconnect}
              className={`px-3 py-1.5 text-xs font-semibold rounded-lg border transition-all cursor-pointer ${isDarkMode ? 'border-slate-800 bg-slate-900/60 text-slate-400 hover:text-slate-200' : 'border-slate-200 bg-white text-slate-600 hover:bg-slate-50'}`}
            >
              Disconnect
            </button>
          </div>
        ) : (
          <button
            onClick={handleAuthorize}
            disabled={isAuthorizing}
            className={`px-4 py-2 text-white text-xs font-bold rounded-xl transition-all shadow-md flex items-center gap-2 hover:scale-[1.02] cursor-pointer ${accentClass} ${isAuthorizing ? 'opacity-50 cursor-not-allowed' : ''}`}
          >
            {isAuthorizing ? (
              <>
                <Loader2 className="w-3.5 h-3.5 animate-spin" /> Authorizing...
              </>
            ) : (
              <>
                <Sparkles className="w-3.5 h-3.5 text-yellow-300" /> Enable Gmail Integration
              </>
            )}
          </button>
        )}
      </div>

      {!token ? (
        /* Unauthorized State Guard Card */
        <div className={`p-12 text-center rounded-2xl border flex flex-col items-center max-w-xl mx-auto space-y-5 ${isDarkMode ? 'bg-slate-950/60 border-slate-800' : 'bg-white border-slate-150 shadow-xs'}`}>
          <div className="p-4 bg-indigo-500/10 rounded-full text-indigo-500">
            <Lock className="w-8 h-8 text-indigo-400" />
          </div>
          <div className="space-y-2">
            <h4 className="font-extrabold text-sm">Secure Gmail Connection Required</h4>
            <p className="text-xs text-slate-400 max-w-sm mx-auto leading-relaxed">
              CSV Auditor Pro uses Google OAuth 2.0 to safely interface with your Gmail. Send reports, contact records directly, or track sent status safely in your dashboard.
            </p>
          </div>
          <button
            onClick={handleAuthorize}
            disabled={isAuthorizing}
            className={`px-5 py-2.5 rounded-xl text-xs font-bold text-white transition-all cursor-pointer shadow-md flex items-center gap-2 ${accentClass}`}
          >
            {isAuthorizing ? <Loader2 className="w-4 h-4 animate-spin" /> : <Mail className="w-4 h-4" />}
            Connect My Gmail Account
          </button>
        </div>
      ) : (
        /* Active Gmail Center Layout */
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          
          {/* Left Column: Sub Tabs & Contact Records Picker */}
          <div className="space-y-6 lg:col-span-1">
            <div className={`rounded-xl border p-4 space-y-4 ${isDarkMode ? 'bg-slate-950/50 border-slate-800' : 'bg-white border-slate-150'}`}>
              <h4 className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block">Operational Tabs</h4>
              <div className="space-y-1">
                {[
                  { id: 'compose', label: 'Compose Auditor Message', icon: Mail },
                  { id: 'contacts', label: 'Extracted CSV Contacts', icon: User, badge: extractedEmails.length },
                  { id: 'sent', label: 'Audit Sent History', icon: Clock }
                ].map((item) => {
                  const Icon = item.icon;
                  const isActive = activeSubTab === item.id;
                  return (
                    <button
                      key={item.id}
                      onClick={() => setActiveSubTab(item.id as any)}
                      className={`w-full px-3 py-2.5 rounded-lg text-xs font-bold flex items-center justify-between transition-all cursor-pointer ${
                        isActive 
                          ? isDarkMode ? 'bg-indigo-500/10 text-indigo-400 border-l-2 border-indigo-500' : 'bg-indigo-50 text-indigo-700 border-l-2 border-indigo-600'
                          : isDarkMode ? 'text-slate-400 hover:text-slate-200 hover:bg-slate-900/40' : 'text-slate-600 hover:bg-slate-50'
                      }`}
                    >
                      <span className="flex items-center gap-2">
                        <Icon className="w-4 h-4" />
                        <span>{item.label}</span>
                      </span>
                      {item.badge !== undefined && item.badge > 0 && (
                        <span className="px-1.5 py-0.5 rounded-full text-[9px] font-bold bg-indigo-500 text-white font-mono shrink-0">
                          {item.badge}
                        </span>
                      )}
                    </button>
                  );
                })}
              </div>
            </div>

            {/* Quick Contacts Autocomplete list */}
            {activeFile && (
              <div className={`rounded-xl border p-4 space-y-4 ${isDarkMode ? 'bg-slate-950/50 border-slate-800' : 'bg-white border-slate-150'}`}>
                <div className="flex justify-between items-center">
                  <h4 className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Active CSV Contacts</h4>
                  <span className="text-[9px] text-indigo-400 font-bold font-mono">Row Index</span>
                </div>
                
                {extractedEmails.length === 0 ? (
                  <p className="text-[10px] text-slate-500 text-center py-2">No email pattern found in current spreadsheet rows.</p>
                ) : (
                  <div className="space-y-1.5 max-h-[220px] overflow-y-auto pr-1">
                    {extractedEmails.map((contact) => (
                      <button
                        key={contact.email}
                        onClick={() => selectContactItem(contact.email)}
                        className={`w-full p-2.5 rounded-lg border text-left transition-all cursor-pointer hover:border-indigo-500/40 flex items-center justify-between ${
                          toEmail === contact.email 
                            ? isDarkMode ? 'bg-indigo-500/5 border-indigo-500/50 text-indigo-300' : 'bg-indigo-50/50 border-indigo-300 text-indigo-950'
                            : isDarkMode ? 'bg-slate-900/40 border-slate-800 text-slate-300' : 'bg-slate-50/40 border-slate-200 text-slate-700'
                        }`}
                      >
                        <div className="min-w-0">
                          <span className="font-bold text-[11px] block truncate">{contact.name}</span>
                          <span className="text-[10px] text-slate-400 font-mono block truncate">{contact.email}</span>
                        </div>
                        <span className="text-[9px] font-bold font-mono bg-slate-800 text-slate-400 px-1.5 py-0.5 rounded shrink-0">
                          Row {contact.row}
                        </span>
                      </button>
                    ))}
                  </div>
                )}
              </div>
            )}
          </div>

          {/* Right Column: Workstations */}
          <div className="lg:col-span-2">
            <AnimatePresence mode="wait">
              
              {/* SUB TAB: COMPOSE FORM */}
              {activeSubTab === 'compose' && (
                <motion.div
                  initial={{ opacity: 0, y: 4 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -4 }}
                  className={`rounded-xl border p-5 space-y-4 ${isDarkMode ? 'bg-slate-950/40 border-slate-800' : 'bg-white border-slate-150'}`}
                >
                  <div className="flex justify-between items-center border-b pb-3 border-slate-800/80">
                    <div>
                      <h3 className="font-bold text-xs">Draft Secure compliance Email</h3>
                      <p className="text-[10px] text-slate-400 mt-0.5">Choose a design template or author custom alerts manually.</p>
                    </div>
                    
                    {/* Template Selector dropdown */}
                    <div className="flex gap-2">
                      <select
                        value={selectedTemplate}
                        onChange={(e: any) => setSelectedTemplate(e.target.value)}
                        className={`px-2 py-1 rounded text-[10px] font-semibold focus:outline-none focus:ring-1 focus:ring-indigo-500 cursor-pointer ${
                          isDarkMode ? 'bg-slate-900 border-slate-800 text-slate-200' : 'bg-slate-100 border-slate-200 text-slate-700'
                        }`}
                      >
                        <option value="audit_summary">Compliance Report Template</option>
                        <option value="hygiene_report">Data Hygiene Correction Alert</option>
                        <option value="custom">Blank Canvas (Custom)</option>
                      </select>
                    </div>
                  </div>

                  {sendSuccess && (
                    <div className="p-3.5 rounded-lg bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 text-xs flex items-center gap-2">
                      <CheckCircle className="w-4 h-4 text-emerald-500" />
                      <span>{sendSuccess}</span>
                    </div>
                  )}

                  {sendError && (
                    <div className="p-3.5 rounded-lg bg-rose-500/10 border border-rose-500/20 text-rose-400 text-xs flex items-center gap-2">
                      <AlertTriangle className="w-4 h-4 text-rose-400" />
                      <span>{sendError}</span>
                    </div>
                  )}

                  <form onSubmit={handleSendEmail} className="space-y-4 text-xs">
                    
                    {/* Recipient Input */}
                    <div className="space-y-1.5">
                      <label className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block">Recipient Address</label>
                      <input 
                        type="email"
                        required
                        value={toEmail}
                        onChange={(e) => setToEmail(e.target.value)}
                        placeholder="client-support@acme.com"
                        className={`w-full px-3 py-2 rounded-lg text-xs font-semibold focus:outline-none focus:ring-1 focus:ring-indigo-500 ${
                          isDarkMode ? 'bg-slate-900 border-slate-800 text-slate-100' : 'bg-white border-slate-200 text-slate-950 border'
                        }`}
                      />
                    </div>

                    {/* Subject Line */}
                    <div className="space-y-1.5">
                      <label className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block">Subject Line</label>
                      <input 
                        type="text"
                        required
                        value={subject}
                        onChange={(e) => setSubject(e.target.value)}
                        placeholder="e.g. Compliance Check Complete"
                        className={`w-full px-3 py-2 rounded-lg text-xs font-semibold focus:outline-none focus:ring-1 focus:ring-indigo-500 ${
                          isDarkMode ? 'bg-slate-900 border-slate-800 text-slate-100' : 'bg-white border-slate-200 text-slate-950 border'
                        }`}
                      />
                    </div>

                    {/* Editor Content Area */}
                    <div className="space-y-1.5">
                      <label className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block">HTML / Text Body</label>
                      <textarea
                        required
                        value={emailBody}
                        onChange={(e) => setEmailBody(e.target.value)}
                        rows={10}
                        placeholder="Dear client, your data was checked..."
                        className={`w-full p-3 font-mono rounded-lg text-xs focus:outline-none focus:ring-1 focus:ring-indigo-500 ${
                          isDarkMode ? 'bg-slate-900 border-slate-800 text-slate-100' : 'bg-white border-slate-200 text-slate-950 border'
                        }`}
                      />
                    </div>

                    {/* Disclaimer and Submit Action */}
                    <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 pt-2">
                      <p className="text-[10px] text-slate-400 max-w-md">
                        *This action drafts an authentic RFC 2822 payload and dispatches it over secure Google endpoints on behalf of your signed-in profile.
                      </p>
                      
                      <button
                        type="submit"
                        disabled={isSending}
                        className={`px-4 py-2 text-white font-bold rounded-xl transition-all shadow-md flex items-center gap-1.5 cursor-pointer hover:scale-[1.01] ${accentClass} ${isSending ? 'opacity-50 cursor-not-allowed' : ''}`}
                      >
                        {isSending ? (
                          <>
                            <Loader2 className="w-3.5 h-3.5 animate-spin" /> Dispatching...
                          </>
                        ) : (
                          <>
                            <Send className="w-3.5 h-3.5" /> Send via Gmail API
                          </>
                        )}
                      </button>
                    </div>

                  </form>
                </motion.div>
              )}

              {/* SUB TAB: EXTRACTED CSV CONTACTS */}
              {activeSubTab === 'contacts' && (
                <motion.div
                  initial={{ opacity: 0, y: 4 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -4 }}
                  className={`rounded-xl border p-5 space-y-4 ${isDarkMode ? 'bg-slate-950/40 border-slate-800' : 'bg-white border-slate-150'}`}
                >
                  <div>
                    <h3 className="font-bold text-xs">Extracted CSV Recipient Ledger</h3>
                    <p className="text-[10px] text-slate-400 mt-0.5">We scanned the rows of your active CSV and extracted valid email patterns for targeted messaging.</p>
                  </div>

                  {extractedEmails.length === 0 ? (
                    <div className="p-8 text-center text-slate-500">
                      <User className="w-8 h-8 text-slate-600 mx-auto mb-2" />
                      <p className="text-xs">No email patterns found in active columns.</p>
                    </div>
                  ) : (
                    <div className="border border-slate-800/80 rounded-xl overflow-hidden text-xs">
                      <table className="w-full text-left">
                        <thead>
                          <tr className={`border-b ${isDarkMode ? 'bg-slate-900 border-slate-800 text-slate-400' : 'bg-slate-50 border-slate-200 text-slate-600'} text-[10px] uppercase font-bold tracking-wider`}>
                            <th className="p-3">Reference Name</th>
                            <th className="p-3">Email Address</th>
                            <th className="p-3">Row Match</th>
                            <th className="p-3 text-right">Quick Action</th>
                          </tr>
                        </thead>
                        <tbody>
                          {extractedEmails.map((item, index) => (
                            <tr key={index} className={`border-b ${isDarkMode ? 'border-slate-800/80 hover:bg-slate-900/40' : 'border-slate-200 hover:bg-slate-50'}`}>
                              <td className="p-3 font-bold">{item.name}</td>
                              <td className="p-3 font-mono">{item.email}</td>
                              <td className="p-3"><span className="px-1.5 py-0.5 rounded bg-slate-800 text-slate-400 font-mono text-[10px]">Row {item.row}</span></td>
                              <td className="p-3 text-right">
                                <button
                                  onClick={() => selectContactItem(item.email)}
                                  className={`px-2.5 py-1 text-[10px] font-bold rounded-lg text-white transition-all cursor-pointer ${accentClass}`}
                                >
                                  Draft Email
                                </button>
                              </td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>
                  )}
                </motion.div>
              )}

              {/* SUB TAB: SENT HISTORY & REAL GMAIL SENT LIST */}
              {activeSubTab === 'sent' && (
                <motion.div
                  initial={{ opacity: 0, y: 4 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -4 }}
                  className={`rounded-xl border p-5 space-y-5 ${isDarkMode ? 'bg-slate-950/40 border-slate-800' : 'bg-white border-slate-150'}`}
                >
                  <div className="flex justify-between items-center">
                    <div>
                      <h3 className="font-bold text-xs">Compliance sent logs</h3>
                      <p className="text-[10px] text-slate-400 mt-0.5">Real-time audit history of emails sent directly through Gmail API.</p>
                    </div>
                    <button
                      onClick={fetchGmailSentList}
                      disabled={isLoadingGmail}
                      className={`p-1.5 rounded-lg border cursor-pointer hover:bg-slate-800 transition-all ${isDarkMode ? 'bg-slate-900 border-slate-800 text-slate-400' : 'bg-white border-slate-200 text-slate-600'}`}
                    >
                      <RefreshCw className={`w-3.5 h-3.5 ${isLoadingGmail ? 'animate-spin text-indigo-400' : ''}`} />
                    </button>
                  </div>

                  {/* Real Sent List from API */}
                  <div className="space-y-3.5">
                    <h4 className="text-[10px] font-bold text-indigo-400 uppercase tracking-widest">Sent via Workspace Gmail API</h4>
                    {isLoadingGmail ? (
                      <div className="p-8 text-center text-slate-400 text-xs">
                        <Loader2 className="w-5 h-5 animate-spin mx-auto text-indigo-400 mb-2" />
                        Scanning secure sent logs...
                      </div>
                    ) : recentGmailMessages.length === 0 ? (
                      <p className="text-[10px] text-slate-500 italic text-center py-4 bg-slate-900/20 rounded-xl border border-slate-800">
                        No recent compliance audit emails detected in your sent mailbox. Try drafting and sending one!
                      </p>
                    ) : (
                      <div className="space-y-2">
                        {recentGmailMessages.map((msg) => (
                          <div 
                            key={msg.id}
                            className={`p-3 rounded-xl border text-left flex justify-between items-start ${isDarkMode ? 'bg-slate-900/60 border-slate-800/80' : 'bg-slate-50 border-slate-200'}`}
                          >
                            <div className="space-y-1 min-w-0">
                              <span className="text-[10px] text-indigo-400 font-mono block">TO: {msg.to}</span>
                              <h5 className="font-bold text-xs truncate max-w-md">{msg.subject}</h5>
                              <span className="text-[9px] text-slate-500 font-medium font-mono">{msg.date}</span>
                            </div>
                            <span className="text-[9px] font-bold text-emerald-400 bg-emerald-500/10 px-2 py-0.5 rounded-full flex items-center gap-1 shrink-0">
                              <Check className="w-3 h-3" /> Sent
                            </span>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>

                  {/* Local Session Logs */}
                  <div className="space-y-3.5 pt-4 border-t border-slate-800/80">
                    <h4 className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">This Session's Logs</h4>
                    <div className="space-y-2">
                      {sentHistory.map((item) => (
                        <div 
                          key={item.id}
                          className={`p-3 rounded-xl border text-left flex justify-between items-start ${isDarkMode ? 'bg-slate-900/40 border-slate-800/50' : 'bg-slate-50/50 border-slate-150'}`}
                        >
                          <div className="space-y-1">
                            <span className="text-[10px] text-indigo-400 font-mono block">TO: {item.to}</span>
                            <h5 className="font-bold text-xs">{item.subject}</h5>
                            <span className="text-[9px] text-slate-500 font-mono">{item.date}</span>
                          </div>
                          <span className={`text-[9px] font-bold px-2 py-0.5 rounded-full ${
                            item.status === 'sent' 
                              ? 'text-emerald-400 bg-emerald-500/10' 
                              : 'text-rose-400 bg-rose-500/10'
                          }`}>
                            {item.status === 'sent' ? 'Sent Success' : 'Failed'}
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>

                </motion.div>
              )}

            </AnimatePresence>
          </div>

        </div>
      )}

    </div>
  );
}
